### ISSUE TITLE
result final_pose / dist_to_goal / angle_to_goal empty

### ISSUE THREAD

**Issue by reinzor** [naturerobots/move_base_flex#127]
Regarding to issue https://github.com/magazino/move_base_flex/issues/24 , this should be fixed but I still get the following outcome:

```
result: 
  outcome: 0
  message: "Controller succeeded; arrived to goal!"
  final_pose: 
    header: 
      seq: 0
      stamp: 
        secs: 0
        nsecs:         0
      frame_id: ''
    pose: 
      position: 
        x: 0.0
        y: 0.0
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 0.0
  dist_to_goal: 0.0
  angle_to_goal: 0.0
```

Could anyone confirm?
