### ISSUE TITLE
Problem with clearing costmap recovery 

### ISSUE THREAD

**Issue by MarcelSoler** [naturerobots/move_base_flex#152]
Hi!
I am using  recovery_action_client to trigger a clear_costmap_recovery. 
The action_client works properly returning succeed. At the move_base_flex node I receive:
```
 Start action "recovery" using recovery "clear_costmap" of type "clear_costmap_recovery/ClearCostmapRecovery"
[ WARN] [/move_base_flex]: Clearing costmap to unstuck robot (3.000000m).
```
All seems to be working properly however  the global_costmap is **not** cleared.
If I do it manually with `rosservice call /move_base_flex/clear_costmaps "{}"`
It works fine.

My recovery_behaviors file:
```
recovery_behaviors:
  - name: 'clear_costmap'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

# clear_costmap:
#  reset_distance: 0.0
```

Am I doing something wrong? 
Any help would be appreciated.

**Comment by nlimpert** [comment]
Maybe related to https://github.com/ros-planning/navigation/pull/641?

**Comment by MarcelSoler** [comment]
I don't think so, I even tried to specify the layers I wanted to clear...

**Comment by corot** [comment]
Hi, I cannot reproduce the problem, as u can see in this sequence:

![2019-08-30_134639](https://user-images.githubusercontent.com/322610/64018485-d8ee3480-cb2c-11e9-98b2-90c2e55ceb0d.gif)

Please check the configuration of the clear_costmaps recovery behavior:

`rosparam get /move_base_flex/clear_costmaps`

Could be that you have configured it to clear only local costmap? This option is available after https://github.com/ros-planning/navigation/commit/ec0ef1e741480be5b370d91e3e1cb612f2d2bf97

Also note that the clear will take some time, depending on the update frequency of your global costmap, and won't take place if its zero.

**Comment by MarcelSoler** [comment]
```
rosparam get /move_base_flex/clear_costmaps
ERROR: Parameter [/move_base_flex/clear_costmaps] is not set
```
Mmmm strange... where is this parameter set?? can you send me an example. Some time ago I used ceres_robot as example

**Comment by corot** [comment]
Well, if you don't have any parameter defined for the clear_costmaps, means u are using the default configuration and so it should clean both costmaps. Btw, I assume your MBF node is called move_base_flex, what can be not the case. Could be also mbf_costmap_nav?  Then change to 

`rosparam get /mbf_costmap_nav/clear_costmaps`

Take a look also at global_costmap/update_frequency, to ensure it's not 0

**Comment by MarcelSoler** [comment]
Update:

I filled all the options just to be sure:

### recovery_behaviors.yaml:
```
recovery_behaviors:
  - name: 'clear_costmap'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

clear_costmap:
  reset_distance: 0.0
  force_updating: true
  affected_maps: both
  layer_names: obstacles_laser rgbd_obstacle_layer
```

### Check ros_params:
```
rosparam get /navigation/move_base_flex/global_costmap/update_frequency
3.0
rosparam get /navigation/move_base_flex/clear_costmap/affected_maps
both
rosparam get /navigation/move_base_flex/clear_costmap/layer_names
obstacles_laser rgbd_obstacle_layer
rosparam get /navigation/move_base_flex/clear_costmap/force_updating
true
rosparam get /navigation/move_base_flex/clear_costmap/reset_distance
0.0
rosparam get /navigation/move_base_flex/clear_costmaps
ERROR: Parameter [/navigation/move_base_flex/clear_costmaps] is not set

```
### results

#### move_base_flex terminal:
```
 Start action "recovery" using recovery "clear_costmap" of type "clear_costmap_recovery/ClearCostmapRecovery"
[ WARN] [/navigation/move_base_flex]: Clearing costmap to unstuck robot (0.000000m).
```

#### goal topic:
```
---
header:
  seq: 48
  stamp:
    secs: 1567418684
    nsecs: 179497169
  frame_id: ''
status:
  goal_id:
    stamp:
      secs: 1567418684
      nsecs: 178718466
    id: "1"
  status: 3
  text: "Recovery \"clear_costmap\" done"
result:
  outcome: 0
  message: "Recovery \"clear_costmap\" done"
  used_plugin: ''

```
It doesn't work, both costmaps don't even flicker...
