### ISSUE TITLE
How to load Recovery Behaviors?

### ISSUE THREAD

**Issue by jack162** [naturerobots/move_base_flex#265]
**When I set a goal for my real robot. It moves a while and stop with some problems.**

[ERROR] [1616142355.497759323]: Received plan with zero length
[ WARN] [1616142355.497839757]: Could not transform the global plan to the frame of the controller
[ WARN] [1616142355.498061408]: The controller has been aborted after it exceeded the patience time
[ WARN] [1616142355.498568957]: No Recovery Behaviors loaded!
[ WARN] [1616142355.498666272]: Abort the execution of the controller: Controller failed

**It seems like i didn't load the Recovery Behaviors. Could anyone told me how to load it?
thanks a lot.**

Here is my params files.
[move_base.yaml]
planners:
  - name: 'navfn/NavfnROS'
    type: 'navfn/NavfnROS'

controllers:
  - name: 'base_local_planner/TrajectoryPlannerROS'
    type: 'base_local_planner/TrajectoryPlannerROS'

controller_frequency: 5.0
controller_patience: 3.0

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

**Comment by spuetz** [comment]
Try to add this in your `move_base.yaml`
```
recovery_behaviors:
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'
  - name: 'clear_costmap'
    type: 'clear_costmap_recovery/ClearCostmapRecover
 ```
