### ISSUE TITLE
Bug with Teb Local Planner? Can't Load Footprint for Trajectory Optimization

### ISSUE THREAD

**Issue by troshyoon** [naturerobots/move_base_flex#283]
EDIT: Solved, thanks dorezyuk!

Hi,

the robot shows a different behavior with **move_base_flex** compared to **move_base** when I'm implementing either the mpc_local_planner and teb_local_planner examples from https://github.com/rst-tu-dortmund/mpc_local_planner and https://github.com/rst-tu-dortmund/teb_local_planner_tutorials. 

Using move_base I could load the robot footprint such as "line", or "polygon". However, with the exact configurations, I got an error: "No robot footprint model specified for trajectory optimization. Using point-shaped model." 

Everything else can be loaded from the teb_local-planner_params.yaml or the mpc_local_planner_params.yaml files except this footprint for trajectory optimization and I don't know why. Any idea?

Some code snippets:

_carlike_minimum_time.launch_
```
        <!--  ************** Navigation ***************  -->
	<node name="move_base_flex" pkg="mbf_costmap_nav" type="mbf_costmap_nav" required="true" output="screen" clear_params="true">
  	  	<rosparam file="$(find mpc_local_planner_examples)/cfg/carlike/costmap_common_params.yaml" command="load" ns="global_costmap" />
  	 	<rosparam file="$(find mpc_local_planner_examples)/cfg/carlike/costmap_common_params.yaml" command="load" ns="local_costmap" />
  		<rosparam file="$(find mpc_local_planner_examples)/cfg/carlike/local_costmap_params.yaml" command="load" />
  		<rosparam file="$(find mpc_local_planner_examples)/cfg/carlike/global_costmap_params.yaml" command="load" />
  		<rosparam file="$(find mpc_local_planner_examples)/cfg/carlike/mpc_local_planner_params.yaml" command="load" />
  		
  		<rosparam file="$(find mpc_local_planner_examples)/cfg/move_base_flex.yaml" command="load"/>

	</node>
	
	<!-- ****************** MBF Goal Relay ******************** -->
        <node name="move_base_relay" pkg="mpc_local_planner_examples" type="mb_relay_subscriber.py"/>

```
_move_base_flex.yaml_
```
planners:
  - name: global_planner/GlobalPlanner
    type: global_planner/GlobalPlanner

controllers:
  - name: mpc_local_planner/MpcLocalPlannerROS
    type: mpc_local_planner/MpcLocalPlannerROS
```
_mpc_local_planner_params.yaml_
```
MpcLocalPlannerROS:
  ## Footprint model for collision avoidance
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "line"
    radius: 0.2 # for type "circular"
    line_start: [0.0, 0.0] # for type "line"
    line_end: [0.4, 0.0] # for type "line"
    is_footprint_dynamic: False
```
