### ISSUE TITLE
Load multiple planners and controllers

### ISSUE THREAD

**Issue by smababou** [naturerobots/move_base_flex#342]
How to initialize multiple planners in launch file for MBF?

**Comment by Rayman** [comment]
Just add more planners to the config:
```yml
controllers:
  - name: planner1
    type: dwa_local_planner/DWAPlannerROS
  - name: planner2
    type: some_other_package/Class
```
